--- 
minimal: 
  artist: "halis duraki"
  title: "deviltux home"
  description: "Software & Security engineer interested in breaking and fixing stuff."
  theme: "sterdo"
posts: 
  in: /posts/i
  out: /posts/o
scripts: 
  - "Trigger Alina POS malware:/scripts/trigger_alina.c"
  - "Get URLs from PE:/scripts/geturls"
art:
  ga: UA-86651245-2
