--- 
minimal: 
  artists: "Halis Duraki"
  title: "deviltux home"
  description: "A home of an engineer and a hacker."
posts: 
  in: /i/posts
  out: /o/posts
scripts: 
  - "Trigger Alina POS malware:/scripts/trigger_alina.c"
  - "Get URLs from PE:/scripts/geturls"
art:
  ga: true 
