baseURL = 'https://duraki.github.io/notes/public'
canonifyURLs=true
relativeURLs=true
uglyURLs=true

buildDrafts=true # => Includes drafts when building
languageCode = 'en-us'
itle = "duraki's notes"
theme = "little-ocean"

copyright = "durakiconsulting (c) h. duraki"
enableEmoji = true # => https://www.webfx.com/tools/emoji-cheat-sheet/
# publishDir = "" # => https://gohugo.io/getting-started/configuration/#publishdir

[permalinks]
posts = '/:title'

[params]
logoUrl = '/favicon.png'
ugly = ".html"
uglyhome = "/index.html"

[params.styles]
