#baseURL = 'https://duraki.github.io/notes/public/'
baseURL = '/notes/public/'

#RelativeURLs=true
#CanonifyURLs=true

languageCode = 'en-us'
title = "duraki's notes"
theme = "little-ocean"

copyright = "durakiconsulting (c) h. duraki"
enableEmoji = true

[permalinks]
posts = '/:title'

[params]
logoUrl = '/favicon.png'

[params.styles]
