# baseURL = 'http://127.0.0.1:8800/notes/public/'
baseURL = 'https://duraki.github.io/notes/public/'
# buildDrafts=true # => Includes drafts when building

#RelativeURLs=true
CanonifyURLs=true

languageCode = 'en-us'
itle = "duraki's notes"
theme = "little-ocean"

copyright = "durakiconsulting (c) h. duraki"
enableEmoji = true # => https://www.webfx.com/tools/emoji-cheat-sheet/
# publishDir = "" # => https://gohugo.io/getting-started/configuration/#publishdir

[permalinks]
posts = '/:title'

[params]
logoUrl = '/favicon.png'

[params.styles]
