languageCode = 'en-us'
title = "Star Wars notes"
themesDir = "../.."
theme = "little-ocean"

[permalinks]
posts = '/:title'

[params]
logoUrl = '/favicon.png'

[params.styles]
  # color = "#fff"
  # backgroundColor = "#000"
  # lineHeight = "1.6"
  # fontFamily = "Arial, sans-serif"

  # headerBackgroundColor = "#111"
  # headerBorderBottomColor = "#666"
  # headerColor = "#fafafa"
  
  # pageBackgroundColor = "#000"
  # pageBorderLeftColor = "#333"
  # pageLinkColor = "#10B981"
  # pageMaxWidth = "625px"
  # pageFontSize = "16px"
  # pageLineHeight = "22px"
  # pageHrBackgroundColor = "#666"

  # backlinksBackgroundColor = "#222"
  # backlinksBorderRadius = "3px"
  # backlinkLabelColor = "#aaa"
  # backlinkTitleColor = "#ccc"
  # backlinkPreviewColor = "#eee"
  # backlinkHoverBackgroundColor = "#444"
  
  # previewWidth = "500px"
  # previewMaxHeight = "350px"
  # previewScale = "0.7"
  # previewBoxShadowTopColor = "rgba(255, 255, 255, 0.08)"
  # previewBoxShadowRightColor = "rgba(255, 255, 255, 0.04)"
  # previewBoxShadowBottomColor = "rgba(255, 255, 255, 0.15)"
  # previewBoxShadowLeftColor = "rgba(255, 255, 255, 0.04)"
  
  # searchExtractColor = "#666"
